
[general]
app_name = "V V V V"
debug = true

[api_url]

# Docker need to load dynamic server url. No need to hardcode here.
#api_base_url = "http://127.0.0.1:8000/admin"
auth_login = "/auth/login"
is_logged_in = "/auth/is_logged_in"
auth_signup = "/auth/signup"

list_states = "/states"
add_state = "/add_state"
update_state = "/update_state"
delete_state = "/delete_state"

list_districts = "/districts_list"
add_district = "/add_district"
update_district = "/update_district"
delete_district = "/delete_district"

list_constituencies = "/assemblyconstituency"
add_constituency = "/add_constituency"
update_constituency = "/update_constituency"
delete_constituency = "/delete_constituency"


[theme]
primaryColor="#1b4332"
backgroundColor="#fff"
secondaryBackgroundColor="#e9ecef"
textColor="#000"
font="sans serif"


[client]

# Whether to enable st.cache.
# Default: true
caching = false


[logger]

toolbarMode = "developer"